/* Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-04-10 12:05:30 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012
--	 Creado por:	Borja Delgado Martin
*/


/*------------------------------------------------------
--  INSERT INITIAL VALUES
------------------------------------------------------*/
USE [tu_cartera_bd]
GO

/*-- User --*/
-- Register users
EXEC	[dbo].[spUserRegister]
 			@user_name = N'Admin', @user_email = N'admin@mail.com', @user_pass = N'12345678'
GO

EXEC	[dbo].[spUserRegister]
 			@user_name = N'Usuario 1', @user_email = N'user1@mail.com', @user_pass = N'12345678'
GO


/*-- Currency --*/
INSERT INTO [dbo].[currency] (name, code) 
VALUES
	('Dolar estadounidense', 'USD'),
	('Euro', 'EUR');


/*-- Portfolio --*/
INSERT INTO [dbo].[portfolio] (name, is_global, description, user_id) 
VALUES 
	('Tecnológicas', 0, 'Empresas tecnológicas', 1),
	('Turísticas', 0, 'Empresas turísticas', 1);


/*-- Ticker --*/
EXEC	[dbo].[spTickersPopulate]
 			@api_key = N'' --Insert external API key
GO


/*-- Portfolio tickers --*/
INSERT INTO [dbo].[portfolio_tickers] (portfolio_id, ticker_id) 
VALUES
	(3, 11),
	(3, 4),
	(4, 831),
	(3, 12);


/*-- Transaction type --*/
INSERT INTO [dbo].[transaction_type] (type, description) 
VALUES
	('Compra', 'Adquisición de acciones de una empresa'),
	('Venta', 'Venta de acciones de una empresa'),
	('Dividendo', 'Reparto de beneficios de la empresa'),
	('Comision', 'Gastos derivados de operar o mantener las acciones');


/*-- Transaction --*/
INSERT INTO [dbo].[transaction] (number_of_shares, unit_price, exchange_to_usd, date, comment, user_id, transaction_type_id, currency_id, ticker_id) 
VALUES 
	(10, 130.84, 0.832086, '2021-02-17', 'Compra 10 en EUR', 1, 1, 2, 11),
	(20, 122.06, 1,  			 '2021-03-03', 'Compra 20 en USD', 1, 1, 1, 11),
	(10, 124.76, 0.841893, '2021-03-17', 'Vende  10 en EUR', 1, 2, 2, 11),
	(30, 122.15, 0.853534, '2021-03-31', 'Compra 30 en EUR', 1, 1, 2, 11),
	(25, 132.03, 1, 			 '2021-04-14', 'Vende  25 en USD', 1, 2, 1, 11),
	(10,  60.78, 1, 			 '2021-02-26', NULL, 1, 1, 1, 4),
	(3,  206.14, 1, 			 '2021-02-26', NULL, 1, 1, 1, 831),
	(5,   59.90, 1, 			 '2021-03-03', NULL, 1, 2, 1, 4),
	(5,  227.56, 1, 			 '2021-03-03', NULL, 1, 1, 1, 12);
