/* Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-04-10 12:05:30 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012
--	 Creado por:	Borja Delgado Martin
*/

/*------------------------------------------------------
--  CREATE DATABASE
------------------------------------------------------*/
DROP DATABASE IF EXISTS tu_cartera_bd
CREATE DATABASE tu_cartera_bd COLLATE Traditional_Spanish_CI_AS


/*------------------------------------------------------
--  CREATE TABLES
------------------------------------------------------*/
CREATE TABLE [tu_cartera_bd].[dbo].[user] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     name VARCHAR (50) NOT NULL , 
     email VARCHAR (200) NOT NULL UNIQUE, 
     pass BINARY(32) NOT NULL ,
     CONSTRAINT user_pk PRIMARY KEY (id)
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[currency] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     code VARCHAR (5) NOT NULL ,
     name VARCHAR (50) NOT NULL , 
     CONSTRAINT currency_pk PRIMARY KEY (id)
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[portfolio] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     name VARCHAR (200) NOT NULL , 
     description TEXT , 
     user_id INTEGER NOT NULL,
     CONSTRAINT portfolio_pk PRIMARY KEY (id) ,
     CONSTRAINT portfolio_user_fk FOREIGN KEY (user_id) REFERENCES [tu_cartera_bd].[dbo].[user](id) 
        ON DELETE CASCADE ON UPDATE CASCADE
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[ticker] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     code VARCHAR (10) NOT NULL , 
     name VARCHAR (200) NOT NULL ,
     CONSTRAINT ticker_pk PRIMARY KEY (id)
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[portfolio_tickers] 
    (
     portfolio_id INTEGER NOT NULL , 
     ticker_id INTEGER NOT NULL ,
     CONSTRAINT portfolio_tickers_pk PRIMARY KEY (portfolio_id,ticker_id) ,
     CONSTRAINT portfolio_tickers_portfolio_fk FOREIGN KEY (portfolio_id) REFERENCES [tu_cartera_bd].[dbo].[portfolio](id) 
        ON DELETE CASCADE ON UPDATE CASCADE ,
     CONSTRAINT portfolio_tickers_ticker_fk FOREIGN KEY (ticker_id) REFERENCES [tu_cartera_bd].[dbo].[ticker](id) 
        ON DELETE CASCADE ON UPDATE CASCADE
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[transaction_type] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     type VARCHAR (50) NOT NULL , 
     description TEXT ,
     CONSTRAINT transaction_type_pk PRIMARY KEY (id) ,
    )
GO

CREATE TABLE [tu_cartera_bd].[dbo].[transaction] 
    (
     id INTEGER NOT NULL IDENTITY(1,1) , 
     number_of_shares NUMERIC (28) NOT NULL , 
     unit_price NUMERIC (28) NOT NULL , 
     date DATE NOT NULL , 
     comment TEXT , 
     user_id INTEGER NOT NULL , 
     transaction_type_id INTEGER NOT NULL , 
     currency_id INTEGER NOT NULL , 
     ticker_id INTEGER NOT NULL ,
     CONSTRAINT transaction_pk PRIMARY KEY (id) ,
     CONSTRAINT transaction_user_fk FOREIGN KEY (user_id) REFERENCES [tu_cartera_bd].[dbo].[user](id) 
        ON DELETE CASCADE ON UPDATE CASCADE ,
     CONSTRAINT transaction_transaction_type_fk FOREIGN KEY (transaction_type_id) REFERENCES [tu_cartera_bd].[dbo].[transaction_type](id) 
        ON DELETE CASCADE ON UPDATE CASCADE ,
     CONSTRAINT transaction_currency_fk FOREIGN KEY (currency_id) REFERENCES [tu_cartera_bd].[dbo].[currency](id) 
        ON DELETE CASCADE ON UPDATE CASCADE ,
     CONSTRAINT transaction_ticker_fk FOREIGN KEY (ticker_id) REFERENCES [tu_cartera_bd].[dbo].[ticker](id) 
        ON DELETE CASCADE ON UPDATE CASCADE
    )
GO


/*------------------------------------------------------
--  CREATE STORED PROCEDURES
------------------------------------------------------*/
USE [tu_cartera_bd]
GO

/*-- Users --*/
-- Description: Get user info
CREATE OR ALTER PROCEDURE [spUserGetLogin]
    @user_id INTEGER
AS
BEGIN
    SET NOCOUNT ON

    SELECT U.[id] as 'user_id', U.[name] as 'user_name', U.[email] as 'user_email'
    FROM [tu_cartera_bd].[dbo].[user] as U
    WHERE U.[id] = @user_id
END
GO

-- Description: Check user credentials
CREATE OR ALTER PROCEDURE [spUserPostLogin]
    @user_email NVARCHAR(200), 
    @user_pass NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @user_id INTEGER;
    DECLARE @passHash BINARY(32);
    SELECT @passHash = HASHBYTES('SHA2_256', @user_pass);
    
    SELECT @user_id = U.[id]
        FROM [dbo].[user] as U 
        WHERE U.[email] = @user_email AND U.[pass] = @passHash;

    IF(@user_id is null)
        SET @user_id = -1

    SELECT @user_id as [user_id]
END
GO

-- Description: Add a new user in the system
CREATE OR ALTER PROCEDURE [spUserRegister]
    @user_name NVARCHAR(50), 
    @user_email NVARCHAR(200), 
    @user_pass NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON

    BEGIN TRY
        DECLARE @passHash BINARY(32);
        SELECT @passHash = HASHBYTES('SHA2_256', @user_pass);

        INSERT INTO [dbo].[user] (name, email, pass)
          VALUES(@user_name, @user_email, @passHash)

        SELECT U.[id] as 'user_id', U.[name] as 'user_name', U.[email] as 'user_email'
            FROM [dbo].[user] as U 
            WHERE U.[email] = @user_email AND U.[pass] = @passHash;
    END TRY
    BEGIN CATCH
    END CATCH
END
GO
